nodeLinker: node-modules

# Yarn configuration for Quater Mobile
# Using Yarn Classic (v1) with node_modules linker

# Network settings
networkTimeout: 300000

# Cache settings
enableGlobalCache: false
