/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/AuditLogs": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get all audit logs with pagination */
    get: {
      parameters: {
        query?: {
          "pageNumber"?: number
          "pageSize"?: number
          "api-version"?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["AuditLogDtoPagedResult"]
            "application/json": components["schemas"]["AuditLogDtoPagedResult"]
            "text/json": components["schemas"]["AuditLogDtoPagedResult"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/AuditLogs/{id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get audit log by ID */
    get: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["AuditLogDto"]
            "application/json": components["schemas"]["AuditLogDto"]
            "text/json": components["schemas"]["AuditLogDto"]
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/AuditLogs/by-entity/{entityId}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get audit logs by entity ID */
    get: {
      parameters: {
        query?: {
          "pageNumber"?: number
          "pageSize"?: number
          "api-version"?: string
        }
        header?: never
        path: {
          entityId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["AuditLogDtoPagedResult"]
            "application/json": components["schemas"]["AuditLogDtoPagedResult"]
            "text/json": components["schemas"]["AuditLogDtoPagedResult"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/AuditLogs/by-user/{userId}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get audit logs by user ID */
    get: {
      parameters: {
        query?: {
          "pageNumber"?: number
          "pageSize"?: number
          "api-version"?: string
        }
        header?: never
        path: {
          userId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["AuditLogDtoPagedResult"]
            "application/json": components["schemas"]["AuditLogDtoPagedResult"]
            "text/json": components["schemas"]["AuditLogDtoPagedResult"]
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/AuditLogs/filter": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Get audit logs with advanced filtering */
    post: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: {
        content: {
          "application/json": components["schemas"]["AuditLogFilterDto"]
          "text/json": components["schemas"]["AuditLogFilterDto"]
          "application/*+json": components["schemas"]["AuditLogFilterDto"]
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["AuditLogDtoPagedResult"]
            "application/json": components["schemas"]["AuditLogDtoPagedResult"]
            "text/json": components["schemas"]["AuditLogDtoPagedResult"]
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/Auth/token": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * OAuth2 token endpoint - handles authorization_code and refresh_token grant types.
     *
     *     For authorization code exchange:
     *       POST /api/auth/token
     *       Content-Type: application/x-www-form-urlencoded
     *
     *       grant_type=authorization_code&code=AUTH_CODE&code_verifier=PKCE_VERIFIER&redirect_uri=quater://oauth/callback&client_id=quater-mobile
     *
     *     For refresh:
     *       POST /api/auth/token
     *       Content-Type: application/x-www-form-urlencoded
     *
     *       grant_type=refresh_token&refresh_token=YOUR_REFRESH_TOKEN
     */
    post: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/Auth/logout": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Logout and revoke all tokens for the user
     * @description This endpoint revokes ALL tokens for the user, effectively logging them out from all devices.
     *     For per-device logout, use the /revoke endpoint with the specific refresh token.
     */
    post: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/Auth/userinfo": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get current user information */
    get: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/auth/authorize": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * OAuth 2.0 authorization endpoint - handles authorization code flow with PKCE.
     *     Accepts both GET and POST as per OAuth 2.0 spec (RFC 6749 Section 3.1).
     *
     *     Query parameters (validated by OpenIddict before reaching this endpoint):
     *       response_type=code (required)
     *       client_id=quater-mobile or quater-desktop (required)
     *       redirect_uri=... (required, validated against registered URIs)
     *       scope=openid email profile offline_access api (optional)
     *       state=... (recommended, returned as-is in redirect)
     *       code_challenge=... (required when PKCE is enforced)
     *       code_challenge_method=S256 (required when PKCE is enforced)
     *
     *     Flow:
     *     1. OpenIddict validates client_id, redirect_uri, code_challenge, code_challenge_method
     *     2. This controller checks if user is authenticated (via cookie)
     *     3. If not authenticated, returns Challenge to redirect to login
     *     4. If authenticated, creates claims principal and issues authorization code
     *     5. Redirects to redirect_uri with code and state parameters
     */
    get: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    /**
     * OAuth 2.0 authorization endpoint - handles authorization code flow with PKCE.
     *     Accepts both GET and POST as per OAuth 2.0 spec (RFC 6749 Section 3.1).
     *
     *     Query parameters (validated by OpenIddict before reaching this endpoint):
     *       response_type=code (required)
     *       client_id=quater-mobile or quater-desktop (required)
     *       redirect_uri=... (required, validated against registered URIs)
     *       scope=openid email profile offline_access api (optional)
     *       state=... (recommended, returned as-is in redirect)
     *       code_challenge=... (required when PKCE is enforced)
     *       code_challenge_method=S256 (required when PKCE is enforced)
     *
     *     Flow:
     *     1. OpenIddict validates client_id, redirect_uri, code_challenge, code_challenge_method
     *     2. This controller checks if user is authenticated (via cookie)
     *     3. If not authenticated, returns Challenge to redirect to login
     *     4. If authenticated, creates claims principal and issues authorization code
     *     5. Redirects to redirect_uri with code and state parameters
     */
    post: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/email-verification/verify": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Verify user email address using a token */
    post: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: {
        content: {
          "application/json": components["schemas"]["VerifyEmailRequest"]
          "text/json": components["schemas"]["VerifyEmailRequest"]
          "application/*+json": components["schemas"]["VerifyEmailRequest"]
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/email-verification/resend": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Resend the email verification link */
    post: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: {
        content: {
          "application/json": components["schemas"]["ResendVerificationRequest"]
          "text/json": components["schemas"]["ResendVerificationRequest"]
          "application/*+json": components["schemas"]["ResendVerificationRequest"]
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/Health/live": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Basic health check endpoint.
     *     Returns 200 OK if the service is running.
     * @description Use this endpoint for liveness probes in Kubernetes.
     *     It only checks if the application is responsive.
     */
    get: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/Health/ready": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Readiness check endpoint.
     *     Returns 200 OK if the service is ready to accept traffic.
     *     Checks database connectivity and other dependencies.
     * @description Use this endpoint for readiness probes in Kubernetes.
     *     It verifies that all dependencies are available.
     */
    get: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Service Unavailable */
        503: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/Health/startup": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Startup check endpoint.
     *     Returns 200 OK if the service has completed startup.
     * @description Use this endpoint for startup probes in Kubernetes.
     *     It helps with slow-starting containers.
     */
    get: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/Health": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Detailed health check endpoint with comprehensive status information. */
    get: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Service Unavailable */
        503: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/Labs": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get all labs with pagination */
    get: {
      parameters: {
        query?: {
          "pageNumber"?: number
          "pageSize"?: number
          "api-version"?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["LabDtoPagedResult"]
            "application/json": components["schemas"]["LabDtoPagedResult"]
            "text/json": components["schemas"]["LabDtoPagedResult"]
          }
        }
      }
    }
    put?: never
    /** Create a new lab */
    post: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CreateLabDto"]
          "text/json": components["schemas"]["CreateLabDto"]
          "application/*+json": components["schemas"]["CreateLabDto"]
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["LabDto"]
            "application/json": components["schemas"]["LabDto"]
            "text/json": components["schemas"]["LabDto"]
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/Labs/active": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get active labs only */
    get: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["LabDto"][]
            "application/json": components["schemas"]["LabDto"][]
            "text/json": components["schemas"]["LabDto"][]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/Labs/{id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get lab by ID */
    get: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["LabDto"]
            "application/json": components["schemas"]["LabDto"]
            "text/json": components["schemas"]["LabDto"]
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    /** Update an existing lab */
    put: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: {
        content: {
          "application/json": components["schemas"]["UpdateLabDto"]
          "text/json": components["schemas"]["UpdateLabDto"]
          "application/*+json": components["schemas"]["UpdateLabDto"]
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["LabDto"]
            "application/json": components["schemas"]["LabDto"]
            "text/json": components["schemas"]["LabDto"]
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    post?: never
    /** Delete a lab (soft delete - marks as inactive) */
    delete: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/Parameters": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get all parameters with pagination */
    get: {
      parameters: {
        query?: {
          "pageNumber"?: number
          "pageSize"?: number
          "api-version"?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ParameterDtoPagedResult"]
            "application/json": components["schemas"]["ParameterDtoPagedResult"]
            "text/json": components["schemas"]["ParameterDtoPagedResult"]
          }
        }
      }
    }
    put?: never
    /** Create a new parameter */
    post: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CreateParameterDto"]
          "text/json": components["schemas"]["CreateParameterDto"]
          "application/*+json": components["schemas"]["CreateParameterDto"]
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ParameterDto"]
            "application/json": components["schemas"]["ParameterDto"]
            "text/json": components["schemas"]["ParameterDto"]
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/Parameters/active": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get active parameters only */
    get: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ParameterDto"][]
            "application/json": components["schemas"]["ParameterDto"][]
            "text/json": components["schemas"]["ParameterDto"][]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/Parameters/{id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get parameter by ID */
    get: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ParameterDto"]
            "application/json": components["schemas"]["ParameterDto"]
            "text/json": components["schemas"]["ParameterDto"]
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    /** Update an existing parameter */
    put: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: {
        content: {
          "application/json": components["schemas"]["UpdateParameterDto"]
          "text/json": components["schemas"]["UpdateParameterDto"]
          "application/*+json": components["schemas"]["UpdateParameterDto"]
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ParameterDto"]
            "application/json": components["schemas"]["ParameterDto"]
            "text/json": components["schemas"]["ParameterDto"]
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    post?: never
    /** Delete a parameter (soft delete - marks as inactive) */
    delete: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/Password/change": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Change password for authenticated user */
    post: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: {
        content: {
          "application/json": components["schemas"]["ChangePasswordRequest"]
          "text/json": components["schemas"]["ChangePasswordRequest"]
          "application/*+json": components["schemas"]["ChangePasswordRequest"]
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/Password/forgot": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Request password reset token (forgot password) */
    post: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: {
        content: {
          "application/json": components["schemas"]["ForgotPasswordRequest"]
          "text/json": components["schemas"]["ForgotPasswordRequest"]
          "application/*+json": components["schemas"]["ForgotPasswordRequest"]
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/Password/reset": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Reset password using a valid token */
    post: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: {
        content: {
          "application/json": components["schemas"]["ResetPasswordRequest"]
          "text/json": components["schemas"]["ResetPasswordRequest"]
          "application/*+json": components["schemas"]["ResetPasswordRequest"]
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/health/email": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/Samples": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get all samples with pagination */
    get: {
      parameters: {
        query?: {
          "pageNumber"?: number
          "pageSize"?: number
          "api-version"?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["SampleDtoPagedResult"]
            "application/json": components["schemas"]["SampleDtoPagedResult"]
            "text/json": components["schemas"]["SampleDtoPagedResult"]
          }
        }
      }
    }
    put?: never
    /** Create a new sample */
    post: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CreateSampleDto"]
          "text/json": components["schemas"]["CreateSampleDto"]
          "application/*+json": components["schemas"]["CreateSampleDto"]
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["SampleDto"]
            "application/json": components["schemas"]["SampleDto"]
            "text/json": components["schemas"]["SampleDto"]
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/Samples/by-lab/{labId}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get samples by lab ID with pagination */
    get: {
      parameters: {
        query?: {
          "pageNumber"?: number
          "pageSize"?: number
          "api-version"?: string
        }
        header?: never
        path: {
          labId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["SampleDtoPagedResult"]
            "application/json": components["schemas"]["SampleDtoPagedResult"]
            "text/json": components["schemas"]["SampleDtoPagedResult"]
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/Samples/{id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get sample by ID */
    get: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["SampleDto"]
            "application/json": components["schemas"]["SampleDto"]
            "text/json": components["schemas"]["SampleDto"]
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    /** Update an existing sample */
    put: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: {
        content: {
          "application/json": components["schemas"]["UpdateSampleDto"]
          "text/json": components["schemas"]["UpdateSampleDto"]
          "application/*+json": components["schemas"]["UpdateSampleDto"]
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["SampleDto"]
            "application/json": components["schemas"]["SampleDto"]
            "text/json": components["schemas"]["SampleDto"]
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    post?: never
    /** Delete a sample (soft delete) */
    delete: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/TestResults": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get all test results with pagination */
    get: {
      parameters: {
        query?: {
          "pageNumber"?: number
          "pageSize"?: number
          "api-version"?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["TestResultDtoPagedResult"]
            "application/json": components["schemas"]["TestResultDtoPagedResult"]
            "text/json": components["schemas"]["TestResultDtoPagedResult"]
          }
        }
      }
    }
    put?: never
    /** Create a new test result */
    post: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CreateTestResultDto"]
          "text/json": components["schemas"]["CreateTestResultDto"]
          "application/*+json": components["schemas"]["CreateTestResultDto"]
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["TestResultDto"]
            "application/json": components["schemas"]["TestResultDto"]
            "text/json": components["schemas"]["TestResultDto"]
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/TestResults/by-sample/{sampleId}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get test results by sample ID with pagination */
    get: {
      parameters: {
        query?: {
          "pageNumber"?: number
          "pageSize"?: number
          "api-version"?: string
        }
        header?: never
        path: {
          sampleId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["TestResultDtoPagedResult"]
            "application/json": components["schemas"]["TestResultDtoPagedResult"]
            "text/json": components["schemas"]["TestResultDtoPagedResult"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/TestResults/{id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get test result by ID */
    get: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["TestResultDto"]
            "application/json": components["schemas"]["TestResultDto"]
            "text/json": components["schemas"]["TestResultDto"]
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    /** Update an existing test result */
    put: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: {
        content: {
          "application/json": components["schemas"]["UpdateTestResultDto"]
          "text/json": components["schemas"]["UpdateTestResultDto"]
          "application/*+json": components["schemas"]["UpdateTestResultDto"]
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["TestResultDto"]
            "application/json": components["schemas"]["TestResultDto"]
            "text/json": components["schemas"]["TestResultDto"]
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    post?: never
    /** Delete a test result (soft delete) */
    delete: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/users/{userId}/labs/{labId}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Adds a user to a lab with the specified role. */
    post: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path: {
          userId: string
          labId: string
        }
        cookie?: never
      }
      requestBody?: {
        content: {
          "application/json": components["schemas"]["AddUserToLabRequest"]
          "text/json": components["schemas"]["AddUserToLabRequest"]
          "application/*+json": components["schemas"]["AddUserToLabRequest"]
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["UserLabDto"]
            "application/json": components["schemas"]["UserLabDto"]
            "text/json": components["schemas"]["UserLabDto"]
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    /** Removes a user from a lab. */
    delete: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path: {
          userId: string
          labId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/users/{userId}/labs/{labId}/role": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Updates a user's role in a specific lab. */
    put: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path: {
          userId: string
          labId: string
        }
        cookie?: never
      }
      requestBody?: {
        content: {
          "application/json": components["schemas"]["UpdateUserRoleRequest"]
          "text/json": components["schemas"]["UpdateUserRoleRequest"]
          "application/*+json": components["schemas"]["UpdateUserRoleRequest"]
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["UserLabDto"]
            "application/json": components["schemas"]["UserLabDto"]
            "text/json": components["schemas"]["UserLabDto"]
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/users/{userId}/labs": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Gets all labs a user belongs to (placeholder for consistency). */
    get: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path: {
          userId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["UserLabDto"][]
            "application/json": components["schemas"]["UserLabDto"][]
            "text/json": components["schemas"]["UserLabDto"][]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/Users": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get all users with pagination */
    get: {
      parameters: {
        query?: {
          "pageNumber"?: number
          "pageSize"?: number
          "api-version"?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["UserDtoPagedResult"]
            "application/json": components["schemas"]["UserDtoPagedResult"]
            "text/json": components["schemas"]["UserDtoPagedResult"]
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    put?: never
    /** Create a new user */
    post: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CreateUserDto"]
          "text/json": components["schemas"]["CreateUserDto"]
          "application/*+json": components["schemas"]["CreateUserDto"]
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["UserDto"]
            "application/json": components["schemas"]["UserDto"]
            "text/json": components["schemas"]["UserDto"]
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/Users/active": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get active users only (non-paginated, useful for dropdowns) */
    get: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["UserDto"][]
            "application/json": components["schemas"]["UserDto"][]
            "text/json": components["schemas"]["UserDto"][]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/Users/by-lab/{labId}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get users by lab ID with pagination */
    get: {
      parameters: {
        query?: {
          "pageNumber"?: number
          "pageSize"?: number
          "api-version"?: string
        }
        header?: never
        path: {
          labId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["UserDtoPagedResult"]
            "application/json": components["schemas"]["UserDtoPagedResult"]
            "text/json": components["schemas"]["UserDtoPagedResult"]
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/Users/{id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get user by ID */
    get: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["UserDto"]
            "application/json": components["schemas"]["UserDto"]
            "text/json": components["schemas"]["UserDto"]
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    /** Update an existing user */
    put: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: {
        content: {
          "application/json": components["schemas"]["UpdateUserDto"]
          "text/json": components["schemas"]["UpdateUserDto"]
          "application/*+json": components["schemas"]["UpdateUserDto"]
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["UserDto"]
            "application/json": components["schemas"]["UserDto"]
            "text/json": components["schemas"]["UserDto"]
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    post?: never
    /** Delete a user (soft delete - marks as inactive) */
    delete: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain": components["schemas"]["ProblemDetails"]
            "application/json": components["schemas"]["ProblemDetails"]
            "text/json": components["schemas"]["ProblemDetails"]
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/Version": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: {
          "api-version"?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** @description Request to add a user to a lab. */
    AddUserToLabRequest: {
      role?: components["schemas"]["UserRole"]
    }
    /**
     * Format: int32
     * @enum {integer}
     */
    AuditAction: 0 | 1 | 2 | 3 | 4
    AuditLogDto: {
      /** Format: uuid */
      id?: string
      /** Format: uuid */
      userId?: string
      userEmail?: string | null
      entityType?: components["schemas"]["EntityType"]
      /** Format: uuid */
      entityId?: string
      action?: components["schemas"]["AuditAction"]
      oldValue?: string | null
      newValue?: string | null
      isTruncated?: boolean
      /** Format: date-time */
      timestamp?: string
      ipAddress?: string | null
      isArchived?: boolean
    }
    AuditLogDtoPagedResult: {
      items?: components["schemas"]["AuditLogDto"][] | null
      /** Format: int32 */
      totalCount?: number
      /** Format: int32 */
      pageNumber?: number
      /** Format: int32 */
      pageSize?: number
      /** Format: int32 */
      readonly totalPages?: number
      readonly hasPreviousPage?: boolean
      readonly hasNextPage?: boolean
    }
    AuditLogFilterDto: {
      entityType?: components["schemas"]["EntityType"]
      /** Format: uuid */
      entityId?: string | null
      /** Format: uuid */
      userId?: string | null
      action?: components["schemas"]["AuditAction"]
      /** Format: date-time */
      startDate?: string | null
      /** Format: date-time */
      endDate?: string | null
      includeArchived?: boolean
      /** Format: int32 */
      pageNumber?: number
      /** Format: int32 */
      pageSize?: number
    }
    /** @description Request model for password change */
    ChangePasswordRequest: {
      currentPassword: string
      newPassword: string
    }
    /**
     * Format: int32
     * @enum {integer}
     */
    ComplianceStatus: 0 | 1 | 2
    CreateLabDto: {
      name: string
      location?: string | null
      contactInfo?: string | null
    }
    CreateParameterDto: {
      name: string
      unit: string
      /** Format: double */
      whoThreshold?: number | null
      /** Format: double */
      minValue?: number | null
      /** Format: double */
      maxValue?: number | null
      description?: string | null
    }
    CreateSampleDto: {
      type: components["schemas"]["SampleType"]
      /** Format: double */
      locationLatitude: number
      /** Format: double */
      locationLongitude: number
      locationDescription?: string | null
      locationHierarchy?: string | null
      /** Format: date-time */
      collectionDate: string
      collectorName: string
      notes?: string | null
      /** Format: uuid */
      labId: string
    }
    CreateTestResultDto: {
      /** Format: uuid */
      sampleId: string
      parameterName: string
      /** Format: double */
      value: number
      unit: string
      /** Format: date-time */
      testDate: string
      technicianName: string
      testMethod: components["schemas"]["TestMethod"]
    }
    CreateUserDto: {
      userName: string
      /** Format: email */
      email: string
      password: string
      role: components["schemas"]["UserRole"]
      /** Format: uuid */
      labId: string
    }
    /**
     * Format: int32
     * @enum {integer}
     */
    EntityType: 1 | 2 | 3 | 4 | 5 | 6
    /** @description Request model for forgot password */
    ForgotPasswordRequest: {
      /** Format: email */
      email: string
    }
    LabDto: {
      /** Format: uuid */
      id?: string
      name?: string | null
      location?: string | null
      contactInfo?: string | null
      /** Format: date-time */
      createdDate?: string
      isActive?: boolean
      /** Format: date-time */
      createdAt?: string
      /** Format: uuid */
      createdBy?: string
      /** Format: date-time */
      updatedAt?: string | null
      /** Format: uuid */
      updatedBy?: string | null
    }
    LabDtoPagedResult: {
      items?: components["schemas"]["LabDto"][] | null
      /** Format: int32 */
      totalCount?: number
      /** Format: int32 */
      pageNumber?: number
      /** Format: int32 */
      pageSize?: number
      /** Format: int32 */
      readonly totalPages?: number
      readonly hasPreviousPage?: boolean
      readonly hasNextPage?: boolean
    }
    ParameterDto: {
      /** Format: uuid */
      id?: string
      name?: string | null
      unit?: string | null
      /** Format: double */
      whoThreshold?: number | null
      /** Format: double */
      minValue?: number | null
      /** Format: double */
      maxValue?: number | null
      description?: string | null
      isActive?: boolean
      /** Format: date-time */
      createdDate?: string
      /** Format: date-time */
      lastModified?: string
    }
    ParameterDtoPagedResult: {
      items?: components["schemas"]["ParameterDto"][] | null
      /** Format: int32 */
      totalCount?: number
      /** Format: int32 */
      pageNumber?: number
      /** Format: int32 */
      pageSize?: number
      /** Format: int32 */
      readonly totalPages?: number
      readonly hasPreviousPage?: boolean
      readonly hasNextPage?: boolean
    }
    ProblemDetails: {
      type?: string | null
      title?: string | null
      /** Format: int32 */
      status?: number | null
      detail?: string | null
      instance?: string | null
    } & {
      [key: string]: unknown
    }
    /** @description Request model for resending verification email */
    ResendVerificationRequest: {
      /** Format: email */
      email: string
    }
    /** @description Request model for resetting password with token */
    ResetPasswordRequest: {
      /** Format: email */
      email: string
      code: string
      newPassword: string
    }
    SampleDto: {
      /** Format: uuid */
      id?: string
      type?: components["schemas"]["SampleType"]
      /** Format: double */
      locationLatitude?: number
      /** Format: double */
      locationLongitude?: number
      locationDescription?: string | null
      locationHierarchy?: string | null
      /** Format: date-time */
      collectionDate?: string
      collectorName?: string | null
      notes?: string | null
      status?: components["schemas"]["SampleStatus"]
      /** Format: int32 */
      version?: number
      /** Format: date-time */
      lastModified?: string
      /** Format: uuid */
      lastModifiedBy?: string
      isDeleted?: boolean
      isSynced?: boolean
      /** Format: uuid */
      labId?: string
      /** Format: uuid */
      createdBy?: string
      /** Format: date-time */
      createdDate?: string
    }
    SampleDtoPagedResult: {
      items?: components["schemas"]["SampleDto"][] | null
      /** Format: int32 */
      totalCount?: number
      /** Format: int32 */
      pageNumber?: number
      /** Format: int32 */
      pageSize?: number
      /** Format: int32 */
      readonly totalPages?: number
      readonly hasPreviousPage?: boolean
      readonly hasNextPage?: boolean
    }
    /**
     * Format: int32
     * @enum {integer}
     */
    SampleStatus: 0 | 1 | 2
    /**
     * Format: int32
     * @enum {integer}
     */
    SampleType: 0 | 1 | 2 | 3 | 4
    /**
     * Format: int32
     * @enum {integer}
     */
    TestMethod: 0 | 1 | 2 | 3 | 4 | 5 | 6
    TestResultDto: {
      /** Format: uuid */
      id?: string
      /** Format: uuid */
      sampleId?: string
      parameterName?: string | null
      /** Format: double */
      value?: number
      unit?: string | null
      /** Format: date-time */
      testDate?: string
      technicianName?: string | null
      testMethod?: components["schemas"]["TestMethod"]
      complianceStatus?: components["schemas"]["ComplianceStatus"]
      /** Format: int32 */
      version?: number
      /** Format: date-time */
      lastModified?: string
      /** Format: uuid */
      lastModifiedBy?: string
      isDeleted?: boolean
      isSynced?: boolean
      /** Format: uuid */
      createdBy?: string
      /** Format: date-time */
      createdDate?: string
    }
    TestResultDtoPagedResult: {
      items?: components["schemas"]["TestResultDto"][] | null
      /** Format: int32 */
      totalCount?: number
      /** Format: int32 */
      pageNumber?: number
      /** Format: int32 */
      pageSize?: number
      /** Format: int32 */
      readonly totalPages?: number
      readonly hasPreviousPage?: boolean
      readonly hasNextPage?: boolean
    }
    UpdateLabDto: {
      name: string
      location?: string | null
      contactInfo?: string | null
      isActive?: boolean
    }
    UpdateParameterDto: {
      name: string
      unit: string
      /** Format: double */
      whoThreshold?: number | null
      /** Format: double */
      minValue?: number | null
      /** Format: double */
      maxValue?: number | null
      description?: string | null
      isActive?: boolean
    }
    UpdateSampleDto: {
      type: components["schemas"]["SampleType"]
      /** Format: double */
      locationLatitude: number
      /** Format: double */
      locationLongitude: number
      locationDescription?: string | null
      locationHierarchy?: string | null
      /** Format: date-time */
      collectionDate: string
      collectorName: string
      notes?: string | null
      status: components["schemas"]["SampleStatus"]
      /** Format: int32 */
      version: number
    }
    UpdateTestResultDto: {
      parameterName: string
      /** Format: double */
      value: number
      unit: string
      /** Format: date-time */
      testDate: string
      technicianName: string
      testMethod: components["schemas"]["TestMethod"]
      /** Format: int32 */
      version: number
    }
    UpdateUserDto: {
      userName?: string | null
      /** Format: email */
      email?: string | null
      role?: components["schemas"]["UserRole"]
      /** Format: uuid */
      labId?: string | null
      isActive?: boolean | null
    }
    /** @description Request to update a user's role in a lab. */
    UpdateUserRoleRequest: {
      role?: components["schemas"]["UserRole"]
    }
    UserDto: {
      /** Format: uuid */
      id?: string
      userName?: string | null
      email?: string | null
      labs?: components["schemas"]["UserLabDto"][] | null
      /** Format: date-time */
      lastLogin?: string | null
      isActive?: boolean
    }
    UserDtoPagedResult: {
      items?: components["schemas"]["UserDto"][] | null
      /** Format: int32 */
      totalCount?: number
      /** Format: int32 */
      pageNumber?: number
      /** Format: int32 */
      pageSize?: number
      /** Format: int32 */
      readonly totalPages?: number
      readonly hasPreviousPage?: boolean
      readonly hasNextPage?: boolean
    }
    UserLabDto: {
      /** Format: uuid */
      labId?: string
      labName: string
      role: components["schemas"]["UserRole"]
      /** Format: date-time */
      assignedAt?: string
    }
    /**
     * Format: int32
     * @enum {integer}
     */
    UserRole: 1 | 2 | 3
    /** @description Request model for email verification */
    VerifyEmailRequest: {
      userId: string
      code: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
