/*
 * Quater Water Quality Management API
 *
 * REST API for managing water quality testing data, compliance calculations, and laboratory operations
 *
 * The version of the OpenAPI document: v1
 * Contact: support@quater.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Quater.Desktop.Api.Client;
using Quater.Desktop.Api.Model;

namespace Quater.Desktop.Api.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IEmailVerificationApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Resend the email verification link
        /// </summary>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="resendVerificationRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void ApiEmailVerificationResendPost(string? apiVersion = default, ResendVerificationRequest? resendVerificationRequest = default, int operationIndex = 0);

        /// <summary>
        /// Resend the email verification link
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="resendVerificationRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ApiEmailVerificationResendPostWithHttpInfo(string? apiVersion = default, ResendVerificationRequest? resendVerificationRequest = default, int operationIndex = 0);
        /// <summary>
        /// Verify user email address using a token
        /// </summary>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="verifyEmailRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void ApiEmailVerificationVerifyPost(string? apiVersion = default, VerifyEmailRequest? verifyEmailRequest = default, int operationIndex = 0);

        /// <summary>
        /// Verify user email address using a token
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="verifyEmailRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ApiEmailVerificationVerifyPostWithHttpInfo(string? apiVersion = default, VerifyEmailRequest? verifyEmailRequest = default, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IEmailVerificationApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Resend the email verification link
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="resendVerificationRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ApiEmailVerificationResendPostAsync(string? apiVersion = default, ResendVerificationRequest? resendVerificationRequest = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Resend the email verification link
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="resendVerificationRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApiEmailVerificationResendPostWithHttpInfoAsync(string? apiVersion = default, ResendVerificationRequest? resendVerificationRequest = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Verify user email address using a token
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="verifyEmailRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ApiEmailVerificationVerifyPostAsync(string? apiVersion = default, VerifyEmailRequest? verifyEmailRequest = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Verify user email address using a token
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="verifyEmailRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApiEmailVerificationVerifyPostWithHttpInfoAsync(string? apiVersion = default, VerifyEmailRequest? verifyEmailRequest = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IEmailVerificationApi : IEmailVerificationApiSync, IEmailVerificationApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class EmailVerificationApi : IEmailVerificationApi
    {
        private Quater.Desktop.Api.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="EmailVerificationApi"/> class.
        /// </summary>
        /// <returns></returns>
        public EmailVerificationApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EmailVerificationApi"/> class.
        /// </summary>
        /// <returns></returns>
        public EmailVerificationApi(string basePath)
        {
            this.Configuration = Quater.Desktop.Api.Client.Configuration.MergeConfigurations(
                Quater.Desktop.Api.Client.GlobalConfiguration.Instance,
                new Quater.Desktop.Api.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Quater.Desktop.Api.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Quater.Desktop.Api.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Quater.Desktop.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EmailVerificationApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public EmailVerificationApi(Quater.Desktop.Api.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Quater.Desktop.Api.Client.Configuration.MergeConfigurations(
                Quater.Desktop.Api.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Quater.Desktop.Api.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Quater.Desktop.Api.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Quater.Desktop.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EmailVerificationApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public EmailVerificationApi(Quater.Desktop.Api.Client.ISynchronousClient client, Quater.Desktop.Api.Client.IAsynchronousClient asyncClient, Quater.Desktop.Api.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Quater.Desktop.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Quater.Desktop.Api.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Quater.Desktop.Api.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Quater.Desktop.Api.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Quater.Desktop.Api.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Resend the email verification link 
        /// </summary>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="resendVerificationRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void ApiEmailVerificationResendPost(string? apiVersion = default, ResendVerificationRequest? resendVerificationRequest = default, int operationIndex = 0)
        {
            ApiEmailVerificationResendPostWithHttpInfo(apiVersion, resendVerificationRequest);
        }

        /// <summary>
        /// Resend the email verification link 
        /// </summary>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="resendVerificationRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Quater.Desktop.Api.Client.ApiResponse<Object> ApiEmailVerificationResendPostWithHttpInfo(string? apiVersion = default, ResendVerificationRequest? resendVerificationRequest = default, int operationIndex = 0)
        {
            Quater.Desktop.Api.Client.RequestOptions localVarRequestOptions = new Quater.Desktop.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = Quater.Desktop.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Quater.Desktop.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (apiVersion != null)
            {
                localVarRequestOptions.QueryParameters.Add(Quater.Desktop.Api.Client.ClientUtils.ParameterToMultiMap("", "api-version", apiVersion));
            }
            localVarRequestOptions.Data = resendVerificationRequest;

            localVarRequestOptions.Operation = "EmailVerificationApi.ApiEmailVerificationResendPost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/api/email_verification/resend", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiEmailVerificationResendPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Resend the email verification link 
        /// </summary>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="resendVerificationRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ApiEmailVerificationResendPostAsync(string? apiVersion = default, ResendVerificationRequest? resendVerificationRequest = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            await ApiEmailVerificationResendPostWithHttpInfoAsync(apiVersion, resendVerificationRequest, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Resend the email verification link 
        /// </summary>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="resendVerificationRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Quater.Desktop.Api.Client.ApiResponse<Object>> ApiEmailVerificationResendPostWithHttpInfoAsync(string? apiVersion = default, ResendVerificationRequest? resendVerificationRequest = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {

            Quater.Desktop.Api.Client.RequestOptions localVarRequestOptions = new Quater.Desktop.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = Quater.Desktop.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Quater.Desktop.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (apiVersion != null)
            {
                localVarRequestOptions.QueryParameters.Add(Quater.Desktop.Api.Client.ClientUtils.ParameterToMultiMap("", "api-version", apiVersion));
            }
            localVarRequestOptions.Data = resendVerificationRequest;

            localVarRequestOptions.Operation = "EmailVerificationApi.ApiEmailVerificationResendPost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/api/email_verification/resend", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiEmailVerificationResendPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Verify user email address using a token 
        /// </summary>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="verifyEmailRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void ApiEmailVerificationVerifyPost(string? apiVersion = default, VerifyEmailRequest? verifyEmailRequest = default, int operationIndex = 0)
        {
            ApiEmailVerificationVerifyPostWithHttpInfo(apiVersion, verifyEmailRequest);
        }

        /// <summary>
        /// Verify user email address using a token 
        /// </summary>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="verifyEmailRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Quater.Desktop.Api.Client.ApiResponse<Object> ApiEmailVerificationVerifyPostWithHttpInfo(string? apiVersion = default, VerifyEmailRequest? verifyEmailRequest = default, int operationIndex = 0)
        {
            Quater.Desktop.Api.Client.RequestOptions localVarRequestOptions = new Quater.Desktop.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = Quater.Desktop.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Quater.Desktop.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (apiVersion != null)
            {
                localVarRequestOptions.QueryParameters.Add(Quater.Desktop.Api.Client.ClientUtils.ParameterToMultiMap("", "api-version", apiVersion));
            }
            localVarRequestOptions.Data = verifyEmailRequest;

            localVarRequestOptions.Operation = "EmailVerificationApi.ApiEmailVerificationVerifyPost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/api/email_verification/verify", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiEmailVerificationVerifyPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Verify user email address using a token 
        /// </summary>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="verifyEmailRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ApiEmailVerificationVerifyPostAsync(string? apiVersion = default, VerifyEmailRequest? verifyEmailRequest = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            await ApiEmailVerificationVerifyPostWithHttpInfoAsync(apiVersion, verifyEmailRequest, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Verify user email address using a token 
        /// </summary>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="verifyEmailRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Quater.Desktop.Api.Client.ApiResponse<Object>> ApiEmailVerificationVerifyPostWithHttpInfoAsync(string? apiVersion = default, VerifyEmailRequest? verifyEmailRequest = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {

            Quater.Desktop.Api.Client.RequestOptions localVarRequestOptions = new Quater.Desktop.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = Quater.Desktop.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Quater.Desktop.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (apiVersion != null)
            {
                localVarRequestOptions.QueryParameters.Add(Quater.Desktop.Api.Client.ClientUtils.ParameterToMultiMap("", "api-version", apiVersion));
            }
            localVarRequestOptions.Data = verifyEmailRequest;

            localVarRequestOptions.Operation = "EmailVerificationApi.ApiEmailVerificationVerifyPost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/api/email_verification/verify", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiEmailVerificationVerifyPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
