/*
 * Quater Water Quality Management API
 *
 * REST API for managing water quality testing data, compliance calculations, and laboratory operations
 *
 * The version of the OpenAPI document: v1
 * Contact: support@quater.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Quater.Desktop.Api.Client;
using Quater.Desktop.Api.Model;

namespace Quater.Desktop.Api.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUserInvitationsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Accept an invitation and activate the user.
        /// </summary>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="acceptInvitationDto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>UserInvitationDto</returns>
        UserInvitationDto ApiInvitationsAcceptPost(string? apiVersion = default, AcceptInvitationDto? acceptInvitationDto = default, int operationIndex = 0);

        /// <summary>
        /// Accept an invitation and activate the user.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="acceptInvitationDto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of UserInvitationDto</returns>
        ApiResponse<UserInvitationDto> ApiInvitationsAcceptPostWithHttpInfo(string? apiVersion = default, AcceptInvitationDto? acceptInvitationDto = default, int operationIndex = 0);
        /// <summary>
        /// Get pending invitations with pagination.
        /// </summary>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="pageSize"> (optional, default to 20)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>UserInvitationDtoPagedResult</returns>
        UserInvitationDtoPagedResult ApiInvitationsGet(int? page = default, int? pageSize = default, string? apiVersion = default, int operationIndex = 0);

        /// <summary>
        /// Get pending invitations with pagination.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="pageSize"> (optional, default to 20)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of UserInvitationDtoPagedResult</returns>
        ApiResponse<UserInvitationDtoPagedResult> ApiInvitationsGetWithHttpInfo(int? page = default, int? pageSize = default, string? apiVersion = default, int operationIndex = 0);
        /// <summary>
        /// Revoke a pending invitation.
        /// </summary>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="invitationId"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void ApiInvitationsInvitationIdDelete(Guid invitationId, string? apiVersion = default, int operationIndex = 0);

        /// <summary>
        /// Revoke a pending invitation.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="invitationId"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ApiInvitationsInvitationIdDeleteWithHttpInfo(Guid invitationId, string? apiVersion = default, int operationIndex = 0);
        /// <summary>
        /// Create a new user invitation.
        /// </summary>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="createUserInvitationDto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>UserInvitationDto</returns>
        UserInvitationDto ApiInvitationsPost(string? apiVersion = default, CreateUserInvitationDto? createUserInvitationDto = default, int operationIndex = 0);

        /// <summary>
        /// Create a new user invitation.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="createUserInvitationDto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of UserInvitationDto</returns>
        ApiResponse<UserInvitationDto> ApiInvitationsPostWithHttpInfo(string? apiVersion = default, CreateUserInvitationDto? createUserInvitationDto = default, int operationIndex = 0);
        /// <summary>
        /// Get an invitation by token.
        /// </summary>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>UserInvitationDto</returns>
        UserInvitationDto ApiInvitationsTokenGet(string token, string? apiVersion = default, int operationIndex = 0);

        /// <summary>
        /// Get an invitation by token.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of UserInvitationDto</returns>
        ApiResponse<UserInvitationDto> ApiInvitationsTokenGetWithHttpInfo(string token, string? apiVersion = default, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUserInvitationsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Accept an invitation and activate the user.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="acceptInvitationDto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UserInvitationDto</returns>
        System.Threading.Tasks.Task<UserInvitationDto> ApiInvitationsAcceptPostAsync(string? apiVersion = default, AcceptInvitationDto? acceptInvitationDto = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Accept an invitation and activate the user.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="acceptInvitationDto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UserInvitationDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<UserInvitationDto>> ApiInvitationsAcceptPostWithHttpInfoAsync(string? apiVersion = default, AcceptInvitationDto? acceptInvitationDto = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Get pending invitations with pagination.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="pageSize"> (optional, default to 20)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UserInvitationDtoPagedResult</returns>
        System.Threading.Tasks.Task<UserInvitationDtoPagedResult> ApiInvitationsGetAsync(int? page = default, int? pageSize = default, string? apiVersion = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get pending invitations with pagination.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="pageSize"> (optional, default to 20)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UserInvitationDtoPagedResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<UserInvitationDtoPagedResult>> ApiInvitationsGetWithHttpInfoAsync(int? page = default, int? pageSize = default, string? apiVersion = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Revoke a pending invitation.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="invitationId"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ApiInvitationsInvitationIdDeleteAsync(Guid invitationId, string? apiVersion = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Revoke a pending invitation.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="invitationId"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApiInvitationsInvitationIdDeleteWithHttpInfoAsync(Guid invitationId, string? apiVersion = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Create a new user invitation.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="createUserInvitationDto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UserInvitationDto</returns>
        System.Threading.Tasks.Task<UserInvitationDto> ApiInvitationsPostAsync(string? apiVersion = default, CreateUserInvitationDto? createUserInvitationDto = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Create a new user invitation.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="createUserInvitationDto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UserInvitationDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<UserInvitationDto>> ApiInvitationsPostWithHttpInfoAsync(string? apiVersion = default, CreateUserInvitationDto? createUserInvitationDto = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Get an invitation by token.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UserInvitationDto</returns>
        System.Threading.Tasks.Task<UserInvitationDto> ApiInvitationsTokenGetAsync(string token, string? apiVersion = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get an invitation by token.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UserInvitationDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<UserInvitationDto>> ApiInvitationsTokenGetWithHttpInfoAsync(string token, string? apiVersion = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUserInvitationsApi : IUserInvitationsApiSync, IUserInvitationsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class UserInvitationsApi : IUserInvitationsApi
    {
        private Quater.Desktop.Api.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="UserInvitationsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public UserInvitationsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UserInvitationsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public UserInvitationsApi(string basePath)
        {
            this.Configuration = Quater.Desktop.Api.Client.Configuration.MergeConfigurations(
                Quater.Desktop.Api.Client.GlobalConfiguration.Instance,
                new Quater.Desktop.Api.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Quater.Desktop.Api.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Quater.Desktop.Api.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Quater.Desktop.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UserInvitationsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public UserInvitationsApi(Quater.Desktop.Api.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Quater.Desktop.Api.Client.Configuration.MergeConfigurations(
                Quater.Desktop.Api.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Quater.Desktop.Api.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Quater.Desktop.Api.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Quater.Desktop.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UserInvitationsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public UserInvitationsApi(Quater.Desktop.Api.Client.ISynchronousClient client, Quater.Desktop.Api.Client.IAsynchronousClient asyncClient, Quater.Desktop.Api.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Quater.Desktop.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Quater.Desktop.Api.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Quater.Desktop.Api.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Quater.Desktop.Api.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Quater.Desktop.Api.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Accept an invitation and activate the user. 
        /// </summary>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="acceptInvitationDto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>UserInvitationDto</returns>
        public UserInvitationDto ApiInvitationsAcceptPost(string? apiVersion = default, AcceptInvitationDto? acceptInvitationDto = default, int operationIndex = 0)
        {
            Quater.Desktop.Api.Client.ApiResponse<UserInvitationDto> localVarResponse = ApiInvitationsAcceptPostWithHttpInfo(apiVersion, acceptInvitationDto);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Accept an invitation and activate the user. 
        /// </summary>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="acceptInvitationDto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of UserInvitationDto</returns>
        public Quater.Desktop.Api.Client.ApiResponse<UserInvitationDto> ApiInvitationsAcceptPostWithHttpInfo(string? apiVersion = default, AcceptInvitationDto? acceptInvitationDto = default, int operationIndex = 0)
        {
            Quater.Desktop.Api.Client.RequestOptions localVarRequestOptions = new Quater.Desktop.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Quater.Desktop.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Quater.Desktop.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (apiVersion != null)
            {
                localVarRequestOptions.QueryParameters.Add(Quater.Desktop.Api.Client.ClientUtils.ParameterToMultiMap("", "api-version", apiVersion));
            }
            localVarRequestOptions.Data = acceptInvitationDto;

            localVarRequestOptions.Operation = "UserInvitationsApi.ApiInvitationsAcceptPost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<UserInvitationDto>("/api/invitations/accept", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiInvitationsAcceptPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Accept an invitation and activate the user. 
        /// </summary>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="acceptInvitationDto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UserInvitationDto</returns>
        public async System.Threading.Tasks.Task<UserInvitationDto> ApiInvitationsAcceptPostAsync(string? apiVersion = default, AcceptInvitationDto? acceptInvitationDto = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            Quater.Desktop.Api.Client.ApiResponse<UserInvitationDto> localVarResponse = await ApiInvitationsAcceptPostWithHttpInfoAsync(apiVersion, acceptInvitationDto, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Accept an invitation and activate the user. 
        /// </summary>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="acceptInvitationDto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UserInvitationDto)</returns>
        public async System.Threading.Tasks.Task<Quater.Desktop.Api.Client.ApiResponse<UserInvitationDto>> ApiInvitationsAcceptPostWithHttpInfoAsync(string? apiVersion = default, AcceptInvitationDto? acceptInvitationDto = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {

            Quater.Desktop.Api.Client.RequestOptions localVarRequestOptions = new Quater.Desktop.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Quater.Desktop.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Quater.Desktop.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (apiVersion != null)
            {
                localVarRequestOptions.QueryParameters.Add(Quater.Desktop.Api.Client.ClientUtils.ParameterToMultiMap("", "api-version", apiVersion));
            }
            localVarRequestOptions.Data = acceptInvitationDto;

            localVarRequestOptions.Operation = "UserInvitationsApi.ApiInvitationsAcceptPost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<UserInvitationDto>("/api/invitations/accept", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiInvitationsAcceptPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get pending invitations with pagination. 
        /// </summary>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="pageSize"> (optional, default to 20)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>UserInvitationDtoPagedResult</returns>
        public UserInvitationDtoPagedResult ApiInvitationsGet(int? page = default, int? pageSize = default, string? apiVersion = default, int operationIndex = 0)
        {
            Quater.Desktop.Api.Client.ApiResponse<UserInvitationDtoPagedResult> localVarResponse = ApiInvitationsGetWithHttpInfo(page, pageSize, apiVersion);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get pending invitations with pagination. 
        /// </summary>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="pageSize"> (optional, default to 20)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of UserInvitationDtoPagedResult</returns>
        public Quater.Desktop.Api.Client.ApiResponse<UserInvitationDtoPagedResult> ApiInvitationsGetWithHttpInfo(int? page = default, int? pageSize = default, string? apiVersion = default, int operationIndex = 0)
        {
            Quater.Desktop.Api.Client.RequestOptions localVarRequestOptions = new Quater.Desktop.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Quater.Desktop.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Quater.Desktop.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(Quater.Desktop.Api.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (pageSize != null)
            {
                localVarRequestOptions.QueryParameters.Add(Quater.Desktop.Api.Client.ClientUtils.ParameterToMultiMap("", "pageSize", pageSize));
            }
            if (apiVersion != null)
            {
                localVarRequestOptions.QueryParameters.Add(Quater.Desktop.Api.Client.ClientUtils.ParameterToMultiMap("", "api-version", apiVersion));
            }

            localVarRequestOptions.Operation = "UserInvitationsApi.ApiInvitationsGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<UserInvitationDtoPagedResult>("/api/invitations", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiInvitationsGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get pending invitations with pagination. 
        /// </summary>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="pageSize"> (optional, default to 20)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UserInvitationDtoPagedResult</returns>
        public async System.Threading.Tasks.Task<UserInvitationDtoPagedResult> ApiInvitationsGetAsync(int? page = default, int? pageSize = default, string? apiVersion = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            Quater.Desktop.Api.Client.ApiResponse<UserInvitationDtoPagedResult> localVarResponse = await ApiInvitationsGetWithHttpInfoAsync(page, pageSize, apiVersion, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get pending invitations with pagination. 
        /// </summary>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="pageSize"> (optional, default to 20)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UserInvitationDtoPagedResult)</returns>
        public async System.Threading.Tasks.Task<Quater.Desktop.Api.Client.ApiResponse<UserInvitationDtoPagedResult>> ApiInvitationsGetWithHttpInfoAsync(int? page = default, int? pageSize = default, string? apiVersion = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {

            Quater.Desktop.Api.Client.RequestOptions localVarRequestOptions = new Quater.Desktop.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Quater.Desktop.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Quater.Desktop.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(Quater.Desktop.Api.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (pageSize != null)
            {
                localVarRequestOptions.QueryParameters.Add(Quater.Desktop.Api.Client.ClientUtils.ParameterToMultiMap("", "pageSize", pageSize));
            }
            if (apiVersion != null)
            {
                localVarRequestOptions.QueryParameters.Add(Quater.Desktop.Api.Client.ClientUtils.ParameterToMultiMap("", "api-version", apiVersion));
            }

            localVarRequestOptions.Operation = "UserInvitationsApi.ApiInvitationsGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<UserInvitationDtoPagedResult>("/api/invitations", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiInvitationsGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Revoke a pending invitation. 
        /// </summary>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="invitationId"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void ApiInvitationsInvitationIdDelete(Guid invitationId, string? apiVersion = default, int operationIndex = 0)
        {
            ApiInvitationsInvitationIdDeleteWithHttpInfo(invitationId, apiVersion);
        }

        /// <summary>
        /// Revoke a pending invitation. 
        /// </summary>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="invitationId"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Quater.Desktop.Api.Client.ApiResponse<Object> ApiInvitationsInvitationIdDeleteWithHttpInfo(Guid invitationId, string? apiVersion = default, int operationIndex = 0)
        {
            Quater.Desktop.Api.Client.RequestOptions localVarRequestOptions = new Quater.Desktop.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Quater.Desktop.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Quater.Desktop.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("invitationId", Quater.Desktop.Api.Client.ClientUtils.ParameterToString(invitationId)); // path parameter
            if (apiVersion != null)
            {
                localVarRequestOptions.QueryParameters.Add(Quater.Desktop.Api.Client.ClientUtils.ParameterToMultiMap("", "api-version", apiVersion));
            }

            localVarRequestOptions.Operation = "UserInvitationsApi.ApiInvitationsInvitationIdDelete";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Delete<Object>("/api/invitations/{invitationId}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiInvitationsInvitationIdDelete", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Revoke a pending invitation. 
        /// </summary>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="invitationId"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ApiInvitationsInvitationIdDeleteAsync(Guid invitationId, string? apiVersion = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            await ApiInvitationsInvitationIdDeleteWithHttpInfoAsync(invitationId, apiVersion, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Revoke a pending invitation. 
        /// </summary>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="invitationId"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Quater.Desktop.Api.Client.ApiResponse<Object>> ApiInvitationsInvitationIdDeleteWithHttpInfoAsync(Guid invitationId, string? apiVersion = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {

            Quater.Desktop.Api.Client.RequestOptions localVarRequestOptions = new Quater.Desktop.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Quater.Desktop.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Quater.Desktop.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("invitationId", Quater.Desktop.Api.Client.ClientUtils.ParameterToString(invitationId)); // path parameter
            if (apiVersion != null)
            {
                localVarRequestOptions.QueryParameters.Add(Quater.Desktop.Api.Client.ClientUtils.ParameterToMultiMap("", "api-version", apiVersion));
            }

            localVarRequestOptions.Operation = "UserInvitationsApi.ApiInvitationsInvitationIdDelete";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.DeleteAsync<Object>("/api/invitations/{invitationId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiInvitationsInvitationIdDelete", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create a new user invitation. 
        /// </summary>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="createUserInvitationDto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>UserInvitationDto</returns>
        public UserInvitationDto ApiInvitationsPost(string? apiVersion = default, CreateUserInvitationDto? createUserInvitationDto = default, int operationIndex = 0)
        {
            Quater.Desktop.Api.Client.ApiResponse<UserInvitationDto> localVarResponse = ApiInvitationsPostWithHttpInfo(apiVersion, createUserInvitationDto);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create a new user invitation. 
        /// </summary>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="createUserInvitationDto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of UserInvitationDto</returns>
        public Quater.Desktop.Api.Client.ApiResponse<UserInvitationDto> ApiInvitationsPostWithHttpInfo(string? apiVersion = default, CreateUserInvitationDto? createUserInvitationDto = default, int operationIndex = 0)
        {
            Quater.Desktop.Api.Client.RequestOptions localVarRequestOptions = new Quater.Desktop.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Quater.Desktop.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Quater.Desktop.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (apiVersion != null)
            {
                localVarRequestOptions.QueryParameters.Add(Quater.Desktop.Api.Client.ClientUtils.ParameterToMultiMap("", "api-version", apiVersion));
            }
            localVarRequestOptions.Data = createUserInvitationDto;

            localVarRequestOptions.Operation = "UserInvitationsApi.ApiInvitationsPost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<UserInvitationDto>("/api/invitations", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiInvitationsPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create a new user invitation. 
        /// </summary>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="createUserInvitationDto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UserInvitationDto</returns>
        public async System.Threading.Tasks.Task<UserInvitationDto> ApiInvitationsPostAsync(string? apiVersion = default, CreateUserInvitationDto? createUserInvitationDto = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            Quater.Desktop.Api.Client.ApiResponse<UserInvitationDto> localVarResponse = await ApiInvitationsPostWithHttpInfoAsync(apiVersion, createUserInvitationDto, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create a new user invitation. 
        /// </summary>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="createUserInvitationDto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UserInvitationDto)</returns>
        public async System.Threading.Tasks.Task<Quater.Desktop.Api.Client.ApiResponse<UserInvitationDto>> ApiInvitationsPostWithHttpInfoAsync(string? apiVersion = default, CreateUserInvitationDto? createUserInvitationDto = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {

            Quater.Desktop.Api.Client.RequestOptions localVarRequestOptions = new Quater.Desktop.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Quater.Desktop.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Quater.Desktop.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (apiVersion != null)
            {
                localVarRequestOptions.QueryParameters.Add(Quater.Desktop.Api.Client.ClientUtils.ParameterToMultiMap("", "api-version", apiVersion));
            }
            localVarRequestOptions.Data = createUserInvitationDto;

            localVarRequestOptions.Operation = "UserInvitationsApi.ApiInvitationsPost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<UserInvitationDto>("/api/invitations", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiInvitationsPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get an invitation by token. 
        /// </summary>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>UserInvitationDto</returns>
        public UserInvitationDto ApiInvitationsTokenGet(string token, string? apiVersion = default, int operationIndex = 0)
        {
            Quater.Desktop.Api.Client.ApiResponse<UserInvitationDto> localVarResponse = ApiInvitationsTokenGetWithHttpInfo(token, apiVersion);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get an invitation by token. 
        /// </summary>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of UserInvitationDto</returns>
        public Quater.Desktop.Api.Client.ApiResponse<UserInvitationDto> ApiInvitationsTokenGetWithHttpInfo(string token, string? apiVersion = default, int operationIndex = 0)
        {
            // verify the required parameter 'token' is set
            if (token == null)
            {
                throw new Quater.Desktop.Api.Client.ApiException(400, "Missing required parameter 'token' when calling UserInvitationsApi->ApiInvitationsTokenGet");
            }

            Quater.Desktop.Api.Client.RequestOptions localVarRequestOptions = new Quater.Desktop.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Quater.Desktop.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Quater.Desktop.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("token", Quater.Desktop.Api.Client.ClientUtils.ParameterToString(token)); // path parameter
            if (apiVersion != null)
            {
                localVarRequestOptions.QueryParameters.Add(Quater.Desktop.Api.Client.ClientUtils.ParameterToMultiMap("", "api-version", apiVersion));
            }

            localVarRequestOptions.Operation = "UserInvitationsApi.ApiInvitationsTokenGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<UserInvitationDto>("/api/invitations/{token}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiInvitationsTokenGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get an invitation by token. 
        /// </summary>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UserInvitationDto</returns>
        public async System.Threading.Tasks.Task<UserInvitationDto> ApiInvitationsTokenGetAsync(string token, string? apiVersion = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            Quater.Desktop.Api.Client.ApiResponse<UserInvitationDto> localVarResponse = await ApiInvitationsTokenGetWithHttpInfoAsync(token, apiVersion, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get an invitation by token. 
        /// </summary>
        /// <exception cref="Quater.Desktop.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UserInvitationDto)</returns>
        public async System.Threading.Tasks.Task<Quater.Desktop.Api.Client.ApiResponse<UserInvitationDto>> ApiInvitationsTokenGetWithHttpInfoAsync(string token, string? apiVersion = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'token' is set
            if (token == null)
            {
                throw new Quater.Desktop.Api.Client.ApiException(400, "Missing required parameter 'token' when calling UserInvitationsApi->ApiInvitationsTokenGet");
            }


            Quater.Desktop.Api.Client.RequestOptions localVarRequestOptions = new Quater.Desktop.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Quater.Desktop.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Quater.Desktop.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("token", Quater.Desktop.Api.Client.ClientUtils.ParameterToString(token)); // path parameter
            if (apiVersion != null)
            {
                localVarRequestOptions.QueryParameters.Add(Quater.Desktop.Api.Client.ClientUtils.ParameterToMultiMap("", "api-version", apiVersion));
            }

            localVarRequestOptions.Operation = "UserInvitationsApi.ApiInvitationsTokenGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<UserInvitationDto>("/api/invitations/{token}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiInvitationsTokenGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
