/*
 * Quater Water Quality Management API
 *
 * REST API for managing water quality testing data, compliance calculations, and laboratory operations
 *
 * The version of the OpenAPI document: v1
 * Contact: support@quater.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Quater.Desktop.Api.Client.OpenAPIDateConverter;

namespace Quater.Desktop.Api.Model
{
    /// <summary>
    /// Request to add a user to a lab.
    /// </summary>
    [DataContract(Name = "AddUserToLabRequest")]
    public partial class AddUserToLabRequest : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Role
        /// </summary>
        [DataMember(Name = "role", EmitDefaultValue = false)]
        public UserRole? Role { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="AddUserToLabRequest" /> class.
        /// </summary>
        /// <param name="role">role.</param>
        public AddUserToLabRequest(UserRole? role = default)
        {
            this.Role = role;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AddUserToLabRequest {\n");
            sb.Append("  Role: ").Append(Role).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
