/*
 * Quater Water Quality Management API
 *
 * REST API for managing water quality testing data, compliance calculations, and laboratory operations
 *
 * The version of the OpenAPI document: v1
 * Contact: support@quater.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Quater.Desktop.Api.Client.OpenAPIDateConverter;

namespace Quater.Desktop.Api.Model
{
    /// <summary>
    /// CreateLabDto
    /// </summary>
    [DataContract(Name = "CreateLabDto")]
    public partial class CreateLabDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateLabDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateLabDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateLabDto" /> class.
        /// </summary>
        /// <param name="name">name (required).</param>
        /// <param name="location">location.</param>
        /// <param name="contactInfo">contactInfo.</param>
        public CreateLabDto(string name = default, string location = default, string contactInfo = default)
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for CreateLabDto and cannot be null");
            }
            this.Name = name;
            this.Location = location;
            this.ContactInfo = contactInfo;
        }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Location
        /// </summary>
        [DataMember(Name = "location", EmitDefaultValue = true)]
        public string Location { get; set; }

        /// <summary>
        /// Gets or Sets ContactInfo
        /// </summary>
        [DataMember(Name = "contactInfo", EmitDefaultValue = true)]
        public string ContactInfo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateLabDto {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Location: ").Append(Location).Append("\n");
            sb.Append("  ContactInfo: ").Append(ContactInfo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) maxLength
            if (this.Name != null && this.Name.Length > 200)
            {
                yield return new ValidationResult("Invalid value for Name, length must be less than 200.", new [] { "Name" });
            }

            // Name (string) minLength
            if (this.Name != null && this.Name.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Name, length must be greater than 1.", new [] { "Name" });
            }

            // Location (string) maxLength
            if (this.Location != null && this.Location.Length > 500)
            {
                yield return new ValidationResult("Invalid value for Location, length must be less than 500.", new [] { "Location" });
            }

            // ContactInfo (string) maxLength
            if (this.ContactInfo != null && this.ContactInfo.Length > 500)
            {
                yield return new ValidationResult("Invalid value for ContactInfo, length must be less than 500.", new [] { "ContactInfo" });
            }

            yield break;
        }
    }

}
