/*
 * Quater Water Quality Management API
 *
 * REST API for managing water quality testing data, compliance calculations, and laboratory operations
 *
 * The version of the OpenAPI document: v1
 * Contact: support@quater.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Quater.Desktop.Api.Client.OpenAPIDateConverter;

namespace Quater.Desktop.Api.Model
{
    /// <summary>
    /// CreateTestResultDto
    /// </summary>
    [DataContract(Name = "CreateTestResultDto")]
    public partial class CreateTestResultDto : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets TestMethod
        /// </summary>
        [DataMember(Name = "testMethod", IsRequired = true, EmitDefaultValue = true)]
        public TestMethod TestMethod { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateTestResultDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateTestResultDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateTestResultDto" /> class.
        /// </summary>
        /// <param name="sampleId">sampleId (required).</param>
        /// <param name="parameterName">parameterName (required).</param>
        /// <param name="value">value (required).</param>
        /// <param name="unit">unit (required).</param>
        /// <param name="testDate">testDate (required).</param>
        /// <param name="technicianName">technicianName (required).</param>
        /// <param name="testMethod">testMethod (required).</param>
        public CreateTestResultDto(Guid sampleId = default, string parameterName = default, double value = default, string unit = default, DateTime testDate = default, string technicianName = default, TestMethod testMethod = default)
        {
            this.SampleId = sampleId;
            // to ensure "parameterName" is required (not null)
            if (parameterName == null)
            {
                throw new ArgumentNullException("parameterName is a required property for CreateTestResultDto and cannot be null");
            }
            this.ParameterName = parameterName;
            this.Value = value;
            // to ensure "unit" is required (not null)
            if (unit == null)
            {
                throw new ArgumentNullException("unit is a required property for CreateTestResultDto and cannot be null");
            }
            this.Unit = unit;
            this.TestDate = testDate;
            // to ensure "technicianName" is required (not null)
            if (technicianName == null)
            {
                throw new ArgumentNullException("technicianName is a required property for CreateTestResultDto and cannot be null");
            }
            this.TechnicianName = technicianName;
            this.TestMethod = testMethod;
        }

        /// <summary>
        /// Gets or Sets SampleId
        /// </summary>
        [DataMember(Name = "sampleId", IsRequired = true, EmitDefaultValue = true)]
        public Guid SampleId { get; set; }

        /// <summary>
        /// Gets or Sets ParameterName
        /// </summary>
        [DataMember(Name = "parameterName", IsRequired = true, EmitDefaultValue = true)]
        public string ParameterName { get; set; }

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [DataMember(Name = "value", IsRequired = true, EmitDefaultValue = true)]
        public double Value { get; set; }

        /// <summary>
        /// Gets or Sets Unit
        /// </summary>
        [DataMember(Name = "unit", IsRequired = true, EmitDefaultValue = true)]
        public string Unit { get; set; }

        /// <summary>
        /// Gets or Sets TestDate
        /// </summary>
        [DataMember(Name = "testDate", IsRequired = true, EmitDefaultValue = true)]
        public DateTime TestDate { get; set; }

        /// <summary>
        /// Gets or Sets TechnicianName
        /// </summary>
        [DataMember(Name = "technicianName", IsRequired = true, EmitDefaultValue = true)]
        public string TechnicianName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateTestResultDto {\n");
            sb.Append("  SampleId: ").Append(SampleId).Append("\n");
            sb.Append("  ParameterName: ").Append(ParameterName).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  Unit: ").Append(Unit).Append("\n");
            sb.Append("  TestDate: ").Append(TestDate).Append("\n");
            sb.Append("  TechnicianName: ").Append(TechnicianName).Append("\n");
            sb.Append("  TestMethod: ").Append(TestMethod).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // ParameterName (string) maxLength
            if (this.ParameterName != null && this.ParameterName.Length > 100)
            {
                yield return new ValidationResult("Invalid value for ParameterName, length must be less than 100.", new [] { "ParameterName" });
            }

            // ParameterName (string) minLength
            if (this.ParameterName != null && this.ParameterName.Length < 1)
            {
                yield return new ValidationResult("Invalid value for ParameterName, length must be greater than 1.", new [] { "ParameterName" });
            }

            // Unit (string) maxLength
            if (this.Unit != null && this.Unit.Length > 20)
            {
                yield return new ValidationResult("Invalid value for Unit, length must be less than 20.", new [] { "Unit" });
            }

            // Unit (string) minLength
            if (this.Unit != null && this.Unit.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Unit, length must be greater than 1.", new [] { "Unit" });
            }

            // TechnicianName (string) maxLength
            if (this.TechnicianName != null && this.TechnicianName.Length > 100)
            {
                yield return new ValidationResult("Invalid value for TechnicianName, length must be less than 100.", new [] { "TechnicianName" });
            }

            // TechnicianName (string) minLength
            if (this.TechnicianName != null && this.TechnicianName.Length < 1)
            {
                yield return new ValidationResult("Invalid value for TechnicianName, length must be greater than 1.", new [] { "TechnicianName" });
            }

            yield break;
        }
    }

}
