/*
 * Quater Water Quality Management API
 *
 * REST API for managing water quality testing data, compliance calculations, and laboratory operations
 *
 * The version of the OpenAPI document: v1
 * Contact: support@quater.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Quater.Desktop.Api.Client.OpenAPIDateConverter;

namespace Quater.Desktop.Api.Model
{
    /// <summary>
    /// Request model for resetting password with token
    /// </summary>
    [DataContract(Name = "ResetPasswordRequest")]
    public partial class ResetPasswordRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ResetPasswordRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ResetPasswordRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ResetPasswordRequest" /> class.
        /// </summary>
        /// <param name="email">The user&#39;s email address. (required).</param>
        /// <param name="code">The password reset code sent to the user&#39;s email. (required).</param>
        /// <param name="newPassword">The new password to set. (required).</param>
        public ResetPasswordRequest(string email = default, string code = default, string newPassword = default)
        {
            // to ensure "email" is required (not null)
            if (email == null)
            {
                throw new ArgumentNullException("email is a required property for ResetPasswordRequest and cannot be null");
            }
            this.Email = email;
            // to ensure "code" is required (not null)
            if (code == null)
            {
                throw new ArgumentNullException("code is a required property for ResetPasswordRequest and cannot be null");
            }
            this.Code = code;
            // to ensure "newPassword" is required (not null)
            if (newPassword == null)
            {
                throw new ArgumentNullException("newPassword is a required property for ResetPasswordRequest and cannot be null");
            }
            this.NewPassword = newPassword;
        }

        /// <summary>
        /// The user&#39;s email address.
        /// </summary>
        /// <value>The user&#39;s email address.</value>
        [DataMember(Name = "email", IsRequired = true, EmitDefaultValue = true)]
        public string Email { get; set; }

        /// <summary>
        /// The password reset code sent to the user&#39;s email.
        /// </summary>
        /// <value>The password reset code sent to the user&#39;s email.</value>
        [DataMember(Name = "code", IsRequired = true, EmitDefaultValue = true)]
        public string Code { get; set; }

        /// <summary>
        /// The new password to set.
        /// </summary>
        /// <value>The new password to set.</value>
        [DataMember(Name = "newPassword", IsRequired = true, EmitDefaultValue = true)]
        public string NewPassword { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ResetPasswordRequest {\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  NewPassword: ").Append(NewPassword).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Email (string) minLength
            if (this.Email != null && this.Email.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Email, length must be greater than 1.", new [] { "Email" });
            }

            // Code (string) minLength
            if (this.Code != null && this.Code.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Code, length must be greater than 1.", new [] { "Code" });
            }

            // NewPassword (string) minLength
            if (this.NewPassword != null && this.NewPassword.Length < 8)
            {
                yield return new ValidationResult("Invalid value for NewPassword, length must be greater than 8.", new [] { "NewPassword" });
            }

            yield break;
        }
    }

}
