/*
 * Quater Water Quality Management API
 *
 * REST API for managing water quality testing data, compliance calculations, and laboratory operations
 *
 * The version of the OpenAPI document: v1
 * Contact: support@quater.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Quater.Desktop.Api.Client.OpenAPIDateConverter;

namespace Quater.Desktop.Api.Model
{
    /// <summary>
    /// UserLabDto
    /// </summary>
    [DataContract(Name = "UserLabDto")]
    public partial class UserLabDto : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Role
        /// </summary>
        [DataMember(Name = "role", IsRequired = true, EmitDefaultValue = true)]
        public UserRole Role { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="UserLabDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UserLabDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UserLabDto" /> class.
        /// </summary>
        /// <param name="labId">labId.</param>
        /// <param name="labName">labName (required).</param>
        /// <param name="role">role (required).</param>
        /// <param name="assignedAt">assignedAt.</param>
        public UserLabDto(Guid labId = default, string labName = default, UserRole role = default, DateTime assignedAt = default)
        {
            // to ensure "labName" is required (not null)
            if (labName == null)
            {
                throw new ArgumentNullException("labName is a required property for UserLabDto and cannot be null");
            }
            this.LabName = labName;
            this.Role = role;
            this.LabId = labId;
            this.AssignedAt = assignedAt;
        }

        /// <summary>
        /// Gets or Sets LabId
        /// </summary>
        [DataMember(Name = "labId", EmitDefaultValue = false)]
        public Guid LabId { get; set; }

        /// <summary>
        /// Gets or Sets LabName
        /// </summary>
        [DataMember(Name = "labName", IsRequired = true, EmitDefaultValue = true)]
        public string LabName { get; set; }

        /// <summary>
        /// Gets or Sets AssignedAt
        /// </summary>
        [DataMember(Name = "assignedAt", EmitDefaultValue = false)]
        public DateTime AssignedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UserLabDto {\n");
            sb.Append("  LabId: ").Append(LabId).Append("\n");
            sb.Append("  LabName: ").Append(LabName).Append("\n");
            sb.Append("  Role: ").Append(Role).Append("\n");
            sb.Append("  AssignedAt: ").Append(AssignedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // LabName (string) maxLength
            if (this.LabName != null && this.LabName.Length > 200)
            {
                yield return new ValidationResult("Invalid value for LabName, length must be less than 200.", new [] { "LabName" });
            }

            // LabName (string) minLength
            if (this.LabName != null && this.LabName.Length < 1)
            {
                yield return new ValidationResult("Invalid value for LabName, length must be greater than 1.", new [] { "LabName" });
            }

            yield break;
        }
    }

}
