/*
 * Quater Water Quality Management API
 *
 * REST API for managing water quality testing data, compliance calculations, and laboratory operations
 *
 * The version of the OpenAPI document: v1
 * Contact: support@quater.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Quater.Desktop.Api.Client;
using Quater.Desktop.Api.Api;
// uncomment below to import models
//using Quater.Desktop.Api.Model;

namespace Quater.Desktop.Api.Test.Api
{
    /// <summary>
    ///  Class for testing EmailVerificationApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class EmailVerificationApiTests : IDisposable
    {
        private EmailVerificationApi instance;

        public EmailVerificationApiTests()
        {
            instance = new EmailVerificationApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmailVerificationApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' EmailVerificationApi
            //Assert.IsType<EmailVerificationApi>(instance);
        }

        /// <summary>
        /// Test ApiEmailVerificationResendPost
        /// </summary>
        [Fact]
        public void ApiEmailVerificationResendPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? apiVersion = null;
            //ResendVerificationRequest? resendVerificationRequest = null;
            //instance.ApiEmailVerificationResendPost(apiVersion, resendVerificationRequest);
        }

        /// <summary>
        /// Test ApiEmailVerificationVerifyPost
        /// </summary>
        [Fact]
        public void ApiEmailVerificationVerifyPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? apiVersion = null;
            //VerifyEmailRequest? verifyEmailRequest = null;
            //instance.ApiEmailVerificationVerifyPost(apiVersion, verifyEmailRequest);
        }
    }
}
