/*
 * Quater Water Quality Management API
 *
 * REST API for managing water quality testing data, compliance calculations, and laboratory operations
 *
 * The version of the OpenAPI document: v1
 * Contact: support@quater.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Quater.Desktop.Api.Model;
using Quater.Desktop.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Quater.Desktop.Api.Test.Model
{
    /// <summary>
    ///  Class for testing AuditAction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AuditActionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AuditAction
        //private AuditAction instance;

        public AuditActionTests()
        {
            // TODO uncomment below to create an instance of AuditAction
            //instance = new AuditAction();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AuditAction
        /// </summary>
        [Fact]
        public void AuditActionInstanceTest()
        {
            // TODO uncomment below to test "IsType" AuditAction
            //Assert.IsType<AuditAction>(instance);
        }
    }
}
