/*
 * Quater Water Quality Management API
 *
 * REST API for managing water quality testing data, compliance calculations, and laboratory operations
 *
 * The version of the OpenAPI document: v1
 * Contact: support@quater.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Quater.Desktop.Api.Model;
using Quater.Desktop.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Quater.Desktop.Api.Test.Model
{
    /// <summary>
    ///  Class for testing LabDtoPagedResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LabDtoPagedResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LabDtoPagedResult
        //private LabDtoPagedResult instance;

        public LabDtoPagedResultTests()
        {
            // TODO uncomment below to create an instance of LabDtoPagedResult
            //instance = new LabDtoPagedResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LabDtoPagedResult
        /// </summary>
        [Fact]
        public void LabDtoPagedResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" LabDtoPagedResult
            //Assert.IsType<LabDtoPagedResult>(instance);
        }

        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Fact]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }

        /// <summary>
        /// Test the property 'TotalCount'
        /// </summary>
        [Fact]
        public void TotalCountTest()
        {
            // TODO unit test for the property 'TotalCount'
        }

        /// <summary>
        /// Test the property 'PageNumber'
        /// </summary>
        [Fact]
        public void PageNumberTest()
        {
            // TODO unit test for the property 'PageNumber'
        }

        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Fact]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }

        /// <summary>
        /// Test the property 'TotalPages'
        /// </summary>
        [Fact]
        public void TotalPagesTest()
        {
            // TODO unit test for the property 'TotalPages'
        }

        /// <summary>
        /// Test the property 'HasPreviousPage'
        /// </summary>
        [Fact]
        public void HasPreviousPageTest()
        {
            // TODO unit test for the property 'HasPreviousPage'
        }

        /// <summary>
        /// Test the property 'HasNextPage'
        /// </summary>
        [Fact]
        public void HasNextPageTest()
        {
            // TODO unit test for the property 'HasNextPage'
        }
    }
}
