/*
 * Quater Water Quality Management API
 *
 * REST API for managing water quality testing data, compliance calculations, and laboratory operations
 *
 * The version of the OpenAPI document: v1
 * Contact: support@quater.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Quater.Desktop.Api.Model;
using Quater.Desktop.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Quater.Desktop.Api.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateLabDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateLabDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateLabDto
        //private UpdateLabDto instance;

        public UpdateLabDtoTests()
        {
            // TODO uncomment below to create an instance of UpdateLabDto
            //instance = new UpdateLabDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateLabDto
        /// </summary>
        [Fact]
        public void UpdateLabDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateLabDto
            //Assert.IsType<UpdateLabDto>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Fact]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }

        /// <summary>
        /// Test the property 'ContactInfo'
        /// </summary>
        [Fact]
        public void ContactInfoTest()
        {
            // TODO unit test for the property 'ContactInfo'
        }

        /// <summary>
        /// Test the property 'IsActive'
        /// </summary>
        [Fact]
        public void IsActiveTest()
        {
            // TODO unit test for the property 'IsActive'
        }
    }
}
