/*
 * Quater Water Quality Management API
 *
 * REST API for managing water quality testing data, compliance calculations, and laboratory operations
 *
 * The version of the OpenAPI document: v1
 * Contact: support@quater.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Quater.Desktop.Api.Model;
using Quater.Desktop.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Quater.Desktop.Api.Test.Model
{
    /// <summary>
    ///  Class for testing UserDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserDto
        //private UserDto instance;

        public UserDtoTests()
        {
            // TODO uncomment below to create an instance of UserDto
            //instance = new UserDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserDto
        /// </summary>
        [Fact]
        public void UserDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserDto
            //Assert.IsType<UserDto>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'UserName'
        /// </summary>
        [Fact]
        public void UserNameTest()
        {
            // TODO unit test for the property 'UserName'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'Labs'
        /// </summary>
        [Fact]
        public void LabsTest()
        {
            // TODO unit test for the property 'Labs'
        }

        /// <summary>
        /// Test the property 'LastLogin'
        /// </summary>
        [Fact]
        public void LastLoginTest()
        {
            // TODO unit test for the property 'LastLogin'
        }

        /// <summary>
        /// Test the property 'IsActive'
        /// </summary>
        [Fact]
        public void IsActiveTest()
        {
            // TODO unit test for the property 'IsActive'
        }
    }
}
