/*
 * Quater Water Quality Management API
 *
 * REST API for managing water quality testing data, compliance calculations, and laboratory operations
 *
 * The version of the OpenAPI document: v1
 * Contact: support@quater.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Quater.Desktop.Api.Model;
using Quater.Desktop.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Quater.Desktop.Api.Test.Model
{
    /// <summary>
    ///  Class for testing UserInfoResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserInfoResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserInfoResponse
        //private UserInfoResponse instance;

        public UserInfoResponseTests()
        {
            // TODO uncomment below to create an instance of UserInfoResponse
            //instance = new UserInfoResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserInfoResponse
        /// </summary>
        [Fact]
        public void UserInfoResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserInfoResponse
            //Assert.IsType<UserInfoResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Sub'
        /// </summary>
        [Fact]
        public void SubTest()
        {
            // TODO unit test for the property 'Sub'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'EmailVerified'
        /// </summary>
        [Fact]
        public void EmailVerifiedTest()
        {
            // TODO unit test for the property 'EmailVerified'
        }
    }
}
