openapi: 3.0.1
info:
  title: Quater API - Auth & Email
  version: v1
paths:
  /api/v1/auth/verify-email:
    post:
      tags:
        - Auth
      summary: Verify user email address using a token
      operationId: verifyEmail
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - userId
                - code
              properties:
                userId:
                  type: string
                  format: uuid
                  description: The user's ID
                code:
                  type: string
                  description: The verification code received via email
      responses:
        '200':
          description: Email successfully verified
        '400':
          description: Invalid token or user ID
        '404':
          description: User not found

  /api/v1/auth/resend-verification:
    post:
      tags:
        - Auth
      summary: Resend the email verification link
      operationId: resendVerification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  format: email
                  description: The user's email address
      responses:
        '200':
          description: Verification email queued (returns 200 even if email not found to prevent enumeration)
        '429':
          description: Too many requests (Rate limit exceeded)

  /api/v1/auth/forgot-password:
    post:
      tags:
        - Auth
      summary: Request a password reset link
      operationId: forgotPassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  format: email
                  description: The registered email address
      responses:
        '200':
          description: Password reset email queued (returns 200 even if email not found to prevent enumeration)
        '429':
          description: Too many requests (Rate limit exceeded)

  /api/v1/auth/reset-password:
    post:
      tags:
        - Auth
      summary: Reset password using a valid token
      operationId: resetPassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - code
                - newPassword
              properties:
                email:
                  type: string
                  format: email
                code:
                  type: string
                  description: The reset token received via email
                newPassword:
                  type: string
                  minLength: 8
                  description: The new password
      responses:
        '200':
          description: Password successfully reset
        '400':
          description: Invalid token or password requirements not met
